#! /bin/sh

set -ex

if [ -z "$OUTPUT_DIRECTORY" ]; then
  OUTPUT_DIRECTORY=$(pwd)
fi

if ! which dch >/dev/null; then
  echo >&2 "please install devscripts"
  exit 1
fi

if ! which debootstrap >/dev/null; then
  echo >&2 "please install debootstrap"
  exit 1
fi

germinate-update-metapackage --vcs --output-directory $OUTPUT_DIRECTORY
sed -i '/ttf-.*/d' $OUTPUT_DIRECTORY/desktop-*amd64
sed -i '/fonts-[^nh].*/d' $OUTPUT_DIRECTORY/desktop-*amd64
sed -i '/fonts-[^nh]/d' $OUTPUT_DIRECTORY/desktop-*amd64
sed -i '/kerneloops-daemon/d' $OUTPUT_DIRECTORY/desktop-*amd64
# kerneloops in 18.04+ is the daemon
sed -i '/kerneloops/d' $OUTPUT_DIRECTORY/desktop-*amd64
sed -i '/whoopsie/d' $OUTPUT_DIRECTORY/desktop-*amd64
sed -i '/^apport$/d' $OUTPUT_DIRECTORY/desktop-*amd64
cd $OUTPUT_DIRECTORY
git checkout debian/changelog
