#! /bin/sh

if ! which dch >/dev/null; then
	echo >&2 "please install devscripts"
	exit 1
fi

if ! which debootstrap >/dev/null; then
	echo >&2 "please install debootstrap"
	exit 1
fi

germinate-update-metapackage --vcs
sed -i '/ttf-.*/d' desktop-recommends-amd64
sed -i '/fonts-[^no].*/d' desktop-recommends-amd64
sed -i '/fonts-[^no]/d' desktop-amd64
git checkout debian/changelog
